# Generated by Django 6.0.7 on 2026-07-17 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('Google', 'Google'), ('Meta', 'Meta'), ('LinkedIn', 'LinkedIn')], max_length=50)),
                ('campaign_name', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('current_stage', models.CharField(choices=[('Not Yet Connected', 'Not Yet Connected'), ('Lead Registered', 'Lead Registered'), ('Initial Contacted', 'Initial Contacted'), ('Site Visited', 'Site Visited'), ('EOI Collected', 'EOI Collected'), ('Booking Confirmed', 'Booking Confirmed')], default='Not Yet Connected', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gtv_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking_date', models.DateField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='attribution_dashboard.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Not Yet Connected', 'Not Yet Connected'), ('Lead Registered', 'Lead Registered'), ('Initial Contacted', 'Initial Contacted'), ('Site Visited', 'Site Visited'), ('EOI Collected', 'EOI Collected'), ('Booking Confirmed', 'Booking Confirmed')], max_length=50)),
                ('date_entered', models.DateField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='attribution_dashboard.lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='attribution_dashboard.project'),
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Google', 'Google'), ('Meta', 'Meta'), ('LinkedIn', 'LinkedIn')], max_length=50)),
                ('campaign_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='attribution_dashboard.project')),
            ],
        ),
    ]
