# Generated by Django 6.0.7 on 2026-07-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_status',
            field=models.CharField(blank=True, choices=[('RNR', 'RNR — Not Picked'), ('Picked', 'Picked Up')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='tag',
            field=models.CharField(choices=[('No Tag', 'No Tag'), ('Cold', 'Cold'), ('Potential', 'Potential'), ('Hot', 'Hot'), ('Super Hot', 'Super Hot')], default='No Tag', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Google', 'Google'), ('Meta', 'Meta'), ('LinkedIn', 'LinkedIn'), ('WhatsApp/SMS', 'WhatsApp/SMS'), ('Alldoors Website', 'Alldoors Website'), ('Data Calling Team', 'Data Calling Team')], max_length=50),
        ),
    ]
