# Generated by Django 6.0.7 on 2026-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution_dashboard', '0002_lead_call_status_lead_tag_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('Not Connected', 'Not Connected'), ('Follow Up', 'Follow Up'), ('Follow Up RNR', 'Follow Up RNR'), ('Not Interested', 'Not Interested'), ('Junk', 'Junk'), ('Interested', 'Interested'), ('Requirement Collected', 'Requirement Collected'), ('Property Changed', 'Property Changed'), ('Visit Dropped', 'Visit Dropped'), ('Visit Unsuccessful', 'Visit Unsuccessful'), ('Closed', 'Closed'), ('Booking Dropped', 'Booking Dropped'), ('Eoi Dropped', 'Eoi Dropped')], max_length=30),
        ),
    ]
