# Generated by Django 6.0.7 on 2026-07-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution_dashboard', '0003_lead_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('leads', 'Leads'), ('ad_spend', 'Ad Spend'), ('bookings', 'Bookings')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('rows_created', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribution_dashboard.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
