# Generated by Django 6.0.7 on 2026-07-21 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution_dashboard', '0004_dataimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='import_type',
            field=models.CharField(choices=[('leads', 'Leads'), ('ad_spend', 'Ad Spend'), ('bookings', 'Bookings'), ('campaign_summary', 'Campaign Summary')], max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Google', 'Google'), ('Meta', 'Meta'), ('LinkedIn', 'LinkedIn')], max_length=50)),
                ('campaign_name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('leads', models.IntegerField(default=0)),
                ('potential', models.IntegerField(default=0)),
                ('hot_super_hot', models.IntegerField(default=0)),
                ('site_visits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribution_dashboard.project')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
    ]
